apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - adguard.yaml
  - atuin.yaml
  - cert-manager.yaml
  - cnpg-system.yaml
  - crowdsec.yaml
  - flux-system.yaml
  - homeassistant.yaml
  - keycloak.yaml
  - kube-system.yaml
  - media.yaml
  - minecraft.yaml
  - monitoring.yaml
  - nextcloud.yaml
  - onepassword.yaml
  - reflector.yaml
  - reloader.yaml
  - valheim.yaml
  - v-rising.yaml
  - wiki-js.yaml

labels:
  - includeSelectors: false
    includeTemplates: false
    namespaceSelectors:
      - matchExpressions:
          - key: kubernetes.io/metadata.name
            operator: NotIn
            values:
              - homeassistant
              - kube-system
    pairs:
      pod-security.kubernetes.io/enforce: baseline
      pod-security.kubernetes.io/enforce-version: latest
      pod-security.kubernetes.io/warn: restricted
      pod-security.kubernetes.io/warn-version: latest
      pod-security.kubernetes.io/audit: restricted
      pod-security.kubernetes.io/audit-version: latest
