apiVersion: v1
kind: Namespace
metadata:
  name: media
  labels:
    # Deluge's VPN container requires privileged mode and a hostPath mount.
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    app.kubernetes.io/component: media-services
    monitored-by: prometheus
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: media
automountServiceAccountToken: false
