apiVersion: v1
kind: Namespace
metadata:
  name: minecraft
  labels:
    app.kubernetes.io/component: game-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: minecraft
automountServiceAccountToken: false
