apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/component: monitoring
    pod-security.kubernetes.io/enforce: privileged
    monitored-by: prometheus
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: monitoring
automountServiceAccountToken: false
