apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud
  labels:
    app.kubernetes.io/component: blob-storage
    monitored-by: prometheus
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: nextcloud
automountServiceAccountToken: false
