apiVersion: v1
kind: Namespace
metadata:
  name: reflector
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    app.kubernetes.io/component: reflector
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: reflector
automountServiceAccountToken: false
