apiVersion: v1
kind: Namespace
metadata:
  name: v-rising
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    app.kubernetes.io/component: game-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: v-rising
automountServiceAccountToken: false
