apiVersion: v1
kind: Namespace
metadata:
  name: valheim
  labels:
    app.kubernetes.io/component: game-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: valheim
automountServiceAccountToken: false
