apiVersion: v1
kind: Namespace
metadata:
  name: wiki
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    app.kubernetes.io/component: wikipedia
    monitored-by: prometheus
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: wiki
automountServiceAccountToken: false
