{
 "title": "Cert Manager",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Cert Manager Controller Container Logs",
   "type": "logs",
   "description": "Logs from the Cert Manager Controller application pod",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"cert-manager-controller\"} |= ``"
    }
   ]
  },
  {
   "title": "Cert Manager Webhook Container Logs",
   "type": "logs",
   "description": "Logs from Cert Manager Webhook application pod",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{container=\"cert-manager-webhook\"} |= ``"
    }
   ]
  },
  {
   "title": "Cert Manager CaInjector Container Logs",
   "type": "logs",
   "description": "Logs from the Cert Manager CaInjector application pod",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{container=\"cert-manager-cainjector\"} |= ``"
    }
   ]
  }
 ]
}