{
 "title": "Nextcloud",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Nextcloud Application Container Logs",
   "type": "logs",
   "description": "Logs from the Nextcloud application pod",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"nextcloud\"} |= ``"
    }
   ]
  },
  {
   "title": "Nextcloud Database Container Logs",
   "type": "logs",
   "description": "Logs from the Nextcloud database pod",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{container=\"nextcloud-postgressql-db\"} |= ``"
    }
   ]
  },
  {
   "title": "Nextcloud Exporter Container Logs",
   "type": "logs",
   "description": "Logs from the Nextcloud Exporter pod",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{container=\"nextcloud-exporter\"} |= ``"
    }
   ]
  },
  {
   "title": "Nextcloud Redis Container Logs",
   "type": "logs",
   "description": "Logs from the Nextcloud redis pod",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "{container=\"nextcloud-redis\"} |= ``"
    }
   ]
  },
  {
   "title": "Nextcloud Cron Container Logs",
   "type": "logs",
   "description": "Logs from the Nextcloud cron pod",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "{container=\"cron\"} |= ``"
    }
   ]
  }
 ]
}