apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sonarr-anime-dashboard-https
  namespace: media
  labels:
    app.kubernetes.io/component: ingress
    app.kubernetes.io/name: sonarr-anime
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`sonarr-anime.powell.place`)
      middlewares:
        - name: security
          namespace: kube-system
      services:
        - name: sonarr-anime
          port: http
