---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: recyclarr
  namespace: media
spec:
  encryptedData:
    secrets.yml: AgAqP3zwdHp2Kdz1wGE8yHqQySte+jd1lvQrrqcSTitf2wZgEYVNAbmag7kvZyCKl2K08IL1aD30AoeSWjU4tN2NGeUFHBJgHr7nV3kwr5ypejY4KG6n5f98+SnAn41uOPT0veXyP5ZU5HsiVn2wBH9YX2XGggBCTL/0gxKsuL2XyxlAecXsAlEwD0yEq+EKsJY1i5meCmZo67EwjZT9NAttdQ7oPkP6HhId5YNoqwoaqPLCYI3pyFMu5Uiwlih5frRmsK7J/29FI/o0vQC9KC/b4Cmbbutt4IsOwfB/ArO0h87bnIvz2scbeY359EXF/6J9y7+rPfZS8xpJDD/2nWStNhFhEJLj3//fxOdulzWbsp9BzMBRS/KQl1uLFL6tbs8do0pE9mSJnB9KLKBX4DKdTdlN7Qam/sJKswRorBWX9mTqiuZoc594ssHFg5xHlq7+ZgKxZpERx7HZCn20E6WMSFsKdU4UcPXoMn57qUNgB6DnqUiI2zYgsrIbWenIRRuVE8sAE0T7wkwMLcb8YD/8UwnjoBAEOTn+chE++9x0LoO0YCG7JAzfmdxanNV/z9/Viba/1/zh6iFgb2NWRr+2jcCGBP+YAKp7WFknnrJcpbmQLdMwHglMbc7dIQXN2r0l2VnpFk436LU8jt44re3r2O3v6h3Ls+tiQNy1WRy8SXw6/nxe42UIj5iabIhrZFXiDKUzqJLRsk9erdlcQRBZ+aJmrKZG5w1+dyDrP9UQePIacdVcCoQ4ztmicA4WyIKe0RgGajVuB9EMfAVgq64FCg1rjkZ3Dl64DWUBkwfDJaWGShm254/JLe3zXPNa3O1TL8PcoSgYfxsWiXRuK7cPZqvYWiH+A8IbuieFifjV4s1CNDECGI6NHesWPVXeog+4ptZvglKKtC8Hn55EgUvjRnNclOPGf3B4GsfpHPuTQKjtAEvjPFsD51XzoNtf87YiMNG2ozkWHMz/FcYRHKPS/lNDvAhk+x96iJnUeMwbE5PdOIm+YuR6dH8nkefLy96HZfwEq5SdNj4y+ytH3LZ8NwTOYa9nNg6yL8hUVROFl6qWrUMJtuy6CBNwV8xRa5plQDPPegUv5DQ=
  template:
    metadata:
      labels:
        app.kubernetes.io/component: secrets
        app.kubernetes.io/name: recyclarr
        app.kubernetes.io/part-of: recyclarr
      name: recyclarr
      namespace: media
    type: Opaque
