apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-cleanup
  namespace: kube-system
  labels:
    app.kubernetes.io/component: service-account
    app.kubernetes.io/name: job-cleanup
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-cleanup
  labels:
    app.kubernetes.io/component: cluster-role
    app.kubernetes.io/name: job-cleanup
rules:
  - apiGroups: ['batch']
    resources: ['jobs']
    verbs: ['get', 'list', 'delete']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: job-cleanup
  labels:
    app.kubernetes.io/component: cluster-role-binding
    app.kubernetes.io/name: job-cleanup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: job-cleanup
subjects:
  - kind: ServiceAccount
    name: job-cleanup
    namespace: kube-system
