#
# Reference:
# https://github.com/WillFantom/overseerr-exporter
#

apiVersion: v1
kind: Service
metadata:
  name: seerr-exporter
  namespace: media
  labels:
    app.kubernetes.io/component: service
    app.kubernetes.io/name: seerr-exporter
spec:
  selector:
    app.kubernetes.io/component: app
    app.kubernetes.io/name: seerr-exporter
  type: ClusterIP
  ports:
    - name: metrics
      port: 9850
      protocol: TCP
      targetPort: metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seerr-exporter
  namespace: media
  labels:
    app.kubernetes.io/component: app
    app.kubernetes.io/name: seerr-exporter
spec:
  revisionHistoryLimit: 1
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: app
      app.kubernetes.io/name: seerr-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/component: app
        app.kubernetes.io/name: seerr-exporter
    spec:
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: abaddon
      containers:
        - name: seerr-exporter
          image: ghcr.io/willfantom/overseerr-exporter:1.2.1 # {"$imagepolicy": "media:seerr-exporter"}
          imagePullPolicy: Always
          args:
            - --overseerr.address=http://seerr.media.svc.cluster.local:5055
            - --overseerr.api-key=$(API_KEY)
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: exportarr
                  key: seerr_api_key
          ports:
            - name: metrics
              containerPort: 9850
              protocol: TCP
