apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: seerr
  namespace: media
spec:
  image: ghcr.io/seerr-team/seerr
  interval: 24h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: seerr
  namespace: media
spec:
  imageRepositoryRef:
    name: seerr
    namespace: media
  policy:
    semver:
      range: '>=1.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: seerr
  namespace: media
spec:
  interval: 24h0m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: FluxCDBot
      messageTemplate: |
        🚨 Image Automation Update 🚨
        {{range .Changed.Changes}}{{print .OldValue}} -> {{println .NewValue}}{{end}}
    push:
      branch: main
  update:
    path: ./apps/media/seerr
    strategy: Setters
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: seerr-exporter
  namespace: media
spec:
  image: ghcr.io/willfantom/overseerr-exporter
  interval: 24h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: seerr-exporter
  namespace: media
spec:
  imageRepositoryRef:
    name: seerr-exporter
  policy:
    semver:
      range: '>=1.2'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: seerr-exporter
  namespace: media
spec:
  interval: 24h0m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: FluxCDBot
      messageTemplate: |
        🚨 Image Automation Update 🚨
        {{range .Changed.Changes}}{{print .OldValue}} -> {{println .NewValue}}{{end}}
    push:
      branch: main
  update:
    path: ./apps/media/seerr
    strategy: Setters
