apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
commonLabels:
  app.kubernetes.io/part-of: alert-manager

secretGenerator:
  - name: alertmanager
    files:
      - alertmanager.yaml
    options:
      disableNameSuffixHash: true
      labels:
        app.kubernetes.io/component: secrets
        app.kubernetes.io/name: alertmanager

resources:
  - deployment.yaml
  - ingress.yaml
  - template.yaml
  - onepassword-item.yaml
