#
# Syncs 1Password item → Secret "crowdsec" in crowdsec namespace.
# Field label in 1Password must be exactly: ENROLL_KEY
# https://developer.1password.com/docs/k8s/operator
#
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: crowdsec
  namespace: crowdsec
  labels:
    app.kubernetes.io/component: secrets
    app.kubernetes.io/name: crowdsec
    app.kubernetes.io/part-of: crowdsec
spec:
  itemPath: vaults/Collective/items/CrowdSec
