apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: bazarr-anime
  namespace: media
spec:
  image: ghcr.io/linuxserver/bazarr
  interval: 24h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: bazarr-anime
  namespace: media
spec:
  imageRepositoryRef:
    name: bazarr-anime
    namespace: media
  policy:
    semver:
      range: '>=1.4.3'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: bazarr-anime
  namespace: media
spec:
  interval: 24h0m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: FluxCDBot
      messageTemplate: |
        🚨 Image Automation Update 🚨
        {{range .Changed.Changes}}{{print .OldValue}} -> {{println .NewValue}}{{end}}
    push:
      branch: main
  update:
    path: ./apps/media/bazarr-anime
    strategy: Setters
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: bazarr-anime-exportarr
  namespace: media
spec:
  interval: 24h0m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: FluxCDBot
      messageTemplate: |
        🚨 Image Automation Update 🚨
        {{range .Changed.Changes}}{{print .OldValue}} -> {{println .NewValue}}{{end}}
    push:
      branch: main
  update:
    path: ./apps/media/bazarr-anime
    strategy: Setters
---
