{
 "title": "Cert Manager",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Cert Manager Controller Container Logs",
   "type": "logs",
   "description": "Logs from the Cert Manager Controller application pod",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"cert-manager-controller\"} |= ``"
    }
   ]
  },
  {
   "title": "Cert Manager Webhook Container Logs",
   "type": "logs",
   "description": "Logs from Cert Manager Webhook application pod",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{container=\"cert-manager-webhook\"} |= ``"
    }
   ]
  },
  {
   "title": "Cert Manager CaInjector Container Logs",
   "type": "logs",
   "description": "Logs from the Cert Manager CaInjector application pod",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{container=\"cert-manager-cainjector\"} |= ``"
    }
   ]
  }
 ]
}
{
 "title": "Home Assistant",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Home Assistant Application Container Logs ",
   "type": "logs",
   "description": "Logs from the Home Assistant application pod",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"homeassistant\"}"
    }
   ]
  },
  {
   "title": "Home Assistant Database Container Logs",
   "type": "logs",
   "description": "Logs from the Home Assistant database pod",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{container=\"homeassistant-postgressql-db\"} |= ``"
    }
   ]
  }
 ]
}
{
 "title": "Keycloak",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Keycloak Application Container Logs",
   "type": "logs",
   "description": "Logs from the Keycloak application pod",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"keycloak\"} |= ``"
    }
   ]
  },
  {
   "title": "Keycloak Database Container Logs",
   "type": "logs",
   "description": "Logs from the Keycloak database pod",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{container=\"keycloak-postgressql-db\"} |= ``"
    }
   ]
  }
 ]
}
{
 "title": "Nextcloud",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Nextcloud Application Container Logs",
   "type": "logs",
   "description": "Logs from the Nextcloud application pod",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"nextcloud\"} |= ``"
    }
   ]
  },
  {
   "title": "Nextcloud Database Container Logs",
   "type": "logs",
   "description": "Logs from the Nextcloud database pod",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{container=\"nextcloud-postgressql-db\"} |= ``"
    }
   ]
  },
  {
   "title": "Nextcloud Exporter Container Logs",
   "type": "logs",
   "description": "Logs from the Nextcloud Exporter pod",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{container=\"nextcloud-exporter\"} |= ``"
    }
   ]
  },
  {
   "title": "Nextcloud Redis Container Logs",
   "type": "logs",
   "description": "Logs from the Nextcloud redis pod",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "{container=\"nextcloud-redis\"} |= ``"
    }
   ]
  },
  {
   "title": "Nextcloud Cron Container Logs",
   "type": "logs",
   "description": "Logs from the Nextcloud cron pod",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "{container=\"cron\"} |= ``"
    }
   ]
  }
 ]
}
{
 "title": "Traefik",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Traefik Application Container Logs",
   "type": "logs",
   "description": "Logs from the Traefik application pod",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"traefik\"} |= ``"
    }
   ]
  },
  {
   "title": "Traefik Forward Auth Container Logs",
   "type": "logs",
   "description": "Logs from the Traefik Forward Auth application pod",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{container=\"traefik-forward-auth\"} |= ``"
    }
   ]
  }
 ]
}
{
 "title": "Wiki.JS",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Wiki.Js Application Container Logs",
   "type": "logs",
   "description": "Logs from the Wiki.Js application pod",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"wiki-js\"} |= ``"
    }
   ]
  },
  {
   "title": "Wiki.Js Database Container Logs",
   "type": "logs",
   "description": "Logs from the Wiki.Js database pod",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{container=\"wiki-js-postgressql-db\"} |= ``"
    }
   ]
  }
 ]
}